Repository Typing-Monkeys/complex-network-link-prediction, pull requests merged in 2023-04, with the labels that each got.

#44 implementato rooted page rank method
  src/social_network_link_prediction/similarity_methods/global_similarity/rooted_page_rank.py
Labels: method

#42 Implementato shortest path
  src/social_network_link_prediction/similarity_methods/global_similarity/shortest_path.py
Labels: method

#40 feature/NMF
  src/social_network_link_prediction/dimensionality_reduction_methods/nmf.py
Labels: method

#39 feature/neighbor_set_inf(single feature)
  src/social_network_link_prediction/other_methods/neighbor_set_information.py
Labels: method

#50 feature/path entropy
  src/social_network_link_prediction/other_methods/information_theory/path_entropy.py
Labels: method

#46 feature/sim rank
  src/social_network_link_prediction/similarity_methods/global_similarity/sim_rank.py
Labels: method

#51 feat(tests): Migliorati unittest
  Makefile
  tests/Configs.py
  tests/dimensionality_reduction/test_svd.py
  tests/similarity_methods/test_global.py
  tests/similarity_methods/test_local.py
  tests/similarity_methods/test_quasi_local.py
  tests/unittests/__init__.py
  tests/unittests/similarity_methods/__init__.py
  tests/unittests/similarity_methods/test_global.py
  tests/unittests/similarity_methods/test_local.py
  tests/unittests/similarity_methods/test_quasi_local.py
  tests/unittests/test_dimreduction.py
  tests/unittests/test_othermethods.py
Labels: enhancement

#49 feat(SBM): Implementato Stochastic Block Model
  src/social_network_link_prediction/probabilistic_methods/__init__.py
  src/social_network_link_prediction/probabilistic_methods/sbm.py
  src/social_network_link_prediction/utils/to_adjacency_matrix.py
Labels: method

#53 NMF fix & only_unconnected function
  src/social_network_link_prediction/dimensionality_reduction_methods/nmf.py
  src/social_network_link_prediction/utils/__init__.py
  src/social_network_link_prediction/utils/nodes_to_indexes.py
  src/social_network_link_prediction/utils/only_unconnected.py
Labels: fix

#55 fix(compatibility): Risolto problema con python < 3.10
  src/social_network_link_prediction/utils/nodes_to_indexes.py
  src/social_network_link_prediction/utils/to_adjacency_matrix.py
Labels: fix

#56 Aggiornamento valori di ritorno
  src/social_network_link_prediction/dimensionality_reduction_methods/svd.py
  src/social_network_link_prediction/similarity_methods/global_similarity/__init__.py
  src/social_network_link_prediction/similarity_methods/global_similarity/random_walk.py
  src/social_network_link_prediction/similarity_methods/global_similarity/rooted_page_rank.py
  src/social_network_link_prediction/similarity_methods/global_similarity/shortest_path.py
Labels: fix

#57 feature/quasi local fix
  src/social_network_link_prediction/similarity_methods/quasi_local_similarity/LPI.py
  src/social_network_link_prediction/similarity_methods/quasi_local_similarity/path_of_length_three.py
Labels: fix

#54 fix(Local Sim): Risolto problema output
  src/social_network_link_prediction/similarity_methods/local_similarity/admic_adar.py
  src/social_network_link_prediction/similarity_methods/local_similarity/common_neighbors.py
  src/social_network_link_prediction/similarity_methods/local_similarity/cosine_similarity.py
  src/social_network_link_prediction/similarity_methods/local_similarity/hub_depressed.py
  src/social_network_link_prediction/similarity_methods/local_similarity/hub_promoted.py
  src/social_network_link_prediction/similarity_methods/local_similarity/jaccard.py
  src/social_network_link_prediction/similarity_methods/local_similarity/node_clustering.py
  src/social_network_link_prediction/similarity_methods/local_similarity/preferential_attachment.py
  src/social_network_link_prediction/similarity_methods/local_similarity/resource_allocation.py
  src/social_network_link_prediction/similarity_methods/local_similarity/sorensen.py
  tests/unittests/similarity_methods/test_local.py
Labels: fix

#59 feat(CI): Aggiunti workflows
  .github/workflows/pypi-production.yml
  .github/workflows/pypi-testing.yml
Labels: enhancement

#58 feat(build & release): Completato target per build e release
  Makefile
  requirements/requirements.txt
  setup.py
Labels: enhancement

#62 docs(README): Aggiunto README
  README.md
  imgs/logo.png
  imgs/logo1.png
  imgs/methods_list.jpg
Labels: documentation
